spring.application.name=api


# Configura a porta da aplicação
server.port=8888


# Desabilita (por enquanto) o acesso a banco de dados
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

#confifura a porta da aplicação


#Desabilita (por enquanto) o acesso a banco de dados

#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://pooled.db.prisma.io:5432/postgres?sslmode=require

spring.datasource.username=88da40cf703e678e1c8e6fddb55b2ae7d14105cde670bcaa97e87b7d46b9b8fc
spring.datasource.password=sk_EZOUDr1qKLcEaQKGFhuR0




