CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  ident_document TEXT NOT NULL,
  birth_date DATE,
  street_name TEXT NOT NULL,
  house_number TEXT NOT NULL,
  complements TEXT,
  district TEXT NOT NULL,
  municipality TEXT NOT NULL,
  state CHAR(2) NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,


  CONSTRAINT pk_customers PRIMARY KEY (id),
  CONSTRAINT uq_customers_ident_document UNIQUE (ident_document),
  CONSTRAINT uq_customers_email UNIQUE (email)
);
