
CREATE TABLE cars (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,


   brand TEXT NOT NULL,
   model TEXT NOT NULL,
   color TEXT NOT NULL,
   year_manufacture INTEGER NOT NULL,
   imported BOOLEAN NOT NULL,
   plates TEXT NOT NULL,
   selling_date DATE,
   selling_price NUMERIC(12,2),


   customer_id BIGINT,


   CONSTRAINT pk_cars PRIMARY KEY (id),


   CONSTRAINT uq_cars_plates UNIQUE (plates),


   CONSTRAINT fk_cars_customer
       FOREIGN KEY (customer_id)
       REFERENCES customers(id)
);

